# Step 1: Specify the base image
FROM python:3.9-slim

# Step 2: Set the working directory inside the container
WORKDIR /app

# Step 3: 
COPY . .

# Step 4: Run the python app
CMD ["python", "app.py"]
