spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/book_social_network
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: prem
    password: prem123
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: NGRtNGtyY2JoanZxcGE0am1hazJsMDlsdmc3ZDczeGc2NmtodDhlNmp4bGY5andwcXZoMXV6MDFnbm1pcG1tdGJ6Z2c1d2pudTVmYXY5YnZsZmxlcTNzeG5icXcyNTV5ODRncWI0aW41b3F1dzY5OHRkM21oN2txYm5icHo0d3A=
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    uploads:
      photos-output-path: ./uploads

server:
  port: 8088